<?php
// $Id: tweetmeme.module,v 1.2.2.2 2009/06/16 23:20:38 robloach Exp $

/**
 * @file
 * Provides integration with the TweetMeme web service (http://tweetmeme.com) to track popular links on Twitter.
 */

function tweetmeme_help($path, $arg) {
  switch ($path) {
    case 'admin/settings/tweetmeme':
    case 'admin/help#tweetmeme':
      return '<p>'. t('<a href="@tweetmeme">TweetMeme</a> provides a way of tracking popular links on <a href="@twitter">Twitter</a>.', array('@tweetmeme' => 'http://tweetmeme.com', '@twitter' => 'http://twitter.com')) .'</p>';
  }
}

/**
 * Implementation of hook_perm().
 */
function tweetmeme_perm() {
  return array(
    'administer tweetmeme',
    'access tweetmeme',
  );
}

/**
 * Implementation of hook_menu().
 */
function tweetmeme_menu() {
  $items['admin/settings/tweetmeme'] = array(
    'title' => 'TweetMeme',
    'description' => 'Provides the configuration options for how TweetMeme operates on the site.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tweetmeme_admin_settings'),
    'access arguments' => array('administer tweetmeme'),
    'file' => 'tweetmeme.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_nodeapi().
 */
function tweetmeme_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  if ($op == 'view') {
    // Make sure we're on the right content type.
    if (!in_array($node->type, variable_get('tweetmeme_types', array()), TRUE)) {
      return NULL;
    }

    // Make sure we're actually building the page to render in a browser.
    if ($node->build_mode != NODE_BUILD_NORMAL) {
      return NULL;
    }

    // Make sure the user has access to use TweetMeme.
    if (!user_access('access tweetmeme')) {
      return NULL;
    }

    // Retrieve the location where we should show it, the style and the URL of the button.
    $location = variable_get('tweetmeme_location', array());
    $style = variable_get('tweetmeme_style', 'normal');
    $url = url('node/' . $node->nid, array('absolute' => TRUE));

    // Check in the teaser view.
    if ($teaser && !empty($location['teasers'])) {
      $node->content['tweetmeme'] = array(
        '#value' => theme('tweetmeme_button', $url, $style),
        '#weight' => -10,
      );
    }
    // Check in the full view.
    else if(!$teaser && !empty($location['content'])) {
      $node->content['tweetmeme'] = array(
        '#value' => theme('tweetmeme_button', $url, $style),
        '#weight' => -10,
      );
    }
  }
}

/**
 * Implementation of hook_theme().
 */
function tweetmeme_theme($existing, $type, $theme, $path) {
  return array(
    'tweetmeme_button' => array(
      'arguments' => array(
        'url' => NULL,
        'style' => NULL,
      ),
    ),
  );
}

/**
 * Displays the TweetMeme button
 */
function theme_tweetmeme_button($url, $style = 'normal') {
  drupal_add_css(drupal_get_path('module', 'tweetmeme') . '/tweetmeme.css');
  $output = '<div class="tweetmeme tweetmeme-button"><script type="text/javascript">tweetmeme_url = "' . $url . '";';
  if ($style != 'normal') {
    $output .= "tweetmeme_style = '$style';";
  }
  $output .= '</script><script type="text/javascript" src="http://tweetmeme.com/i/scripts/button.js"></script></div>';
  return $output;
}
